# gripper controller 
gripper_controller:
  gains:
    robotiq_85_left_knuckle_joint:
      p: 10.0 
  type: position_controllers/JointTrajectoryController
  joints: [robotiq_85_left_knuckle_joint]
  allow_partial_joints_goal: true