wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 2.7.12
    t:
      1:
      - 3
      2:
      - 3
      4: 2.7.12
      5: 0.10.20
