aubo_i5: #namespace

    #qlearn parameters
    alpha: 0.1
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999

    nepisodes: 500
    nsteps: 10000

    n_actions: 14 # Increase and decrease 7 joints.   #X

    work_space: # 3D cube in which Sawyers TCP ( right_electric_gripper_base frame) is allowed to move in
      x_max: 1.1                                      #X
      x_min: 0.0                                      #X
      y_max: 1.0                                      #X
      y_min: -1.0                                     #X
      z_max: 1.3                                      #X
      z_min: 0.3                                      #X


    acceptable_distance_to_cube: 0.16 # Distance to the clock that we consider that it reached the block.                                       #X
    tcp_z_position_min: 0.83 # Z value minimum to consider that the tcp is above the table, to avoid cheating the block distance done.        #X
    
    max_effort: 50.0 # Maximum Effort , above which the episode is done.  #X
    
    number_decimals_precision_obs: 1                                      #X

    done_reward: 1000.0 # reward
    closer_to_block_reward: 100.0 # reward                                #X